version: "3"
services:
  kntrl:
    image: kntrl/self-hosted:0.9
    volumes:
    - "./kntrl.json5:/kntrl/kntrl.json5"
    ports:
    - "9876:9876"
    depends_on:
    - mysql

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: test-pass
      MYSQL_DATABASE: test
      MYSQL_USER: test-user
      MYSQL_PASSWORD: test-pass
    volumes:
      - "./mysql:/var/lib/mysql"
    ports:
      - "3306:3306"