version: "3"
services:
  kntrl:
    image: kntrl/self-hosted:0.9
    volumes:
    - "kntrl.json5:/kntrl/kntrl.json5"

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: test
      MONGO_INITDB_ROOT_USERNAME: test-user
      MONGO_INITDB_ROOT_PASSWORD: test-pass
    ports:
      - "27017:27017"