import {Kntrl} from '../../.client/node_modules/kntrl-client/index.js';
import totp from '../../.client/node_modules/totp-generator/index.js';
import Prompt from '../../.client/node_modules/prompt-sync/index.js';

const prompt = Prompt({});

async function example() {
  const username = `John-${Math.random()}`;

  // Sign up with username and password
  const signUpSession = new Kntrl().newSession({
    entry: 'app',
    logins: {
      username
    },
    signUp: true,
  });
  await signUpSession.authenticate({
    authReqs: {
      password: {
        password: 'Abcdef1@'
      },
    }
  });

  // Enable TOTP:
  const totpEnableRes = await signUpSession.user.save({
    factors: {
      second: true
    },
    authReqs: {
      totp: {
        issuer: 'Example',
        accountName: username,
      }
    }
  });
  // Show generate totp url. QR code is generated too.
  console.log('Add TOTP key to any TOTP app: ' + totpEnableRes.authRes.totp.resData.secret +
  ' or use URL: ' + totpEnableRes.authRes.totp.resData.otpUrl);


  const signInSession = new Kntrl().newSession({
    entry: 'app',
    logins: {
      username,
    },
    signIn: true,
  });
  let signInRes = await signInSession.authenticate({
    authReqs: {
      password: {
        password: 'Abcdef1@',
      },
    }
  });
  if (signInRes.session.nextFactors.length > 0 && signInRes.session.nextFactors[0].supportedAuths.includes('totp')) {
    signInRes = await signInSession.authenticate({
      authReqs: {
        totp: {
          code: prompt('TOTP code is required. Enter code from app, or press enter to use code generated by this script: ')
            || totp(totpEnableRes.authRes.totp.resData.secret),
        }
      }
    });
  }
  console.log(signInRes.authRes)
}

example().catch(err => console.log(err));