version: "3"
services:
  kntrl:
    image: kntrl/self-hosted:0.10.0
    volumes:
    - "./kntrl.json5:/kntrl/kntrl.json5"
    ports:
    - "9876:9876"
    depends_on:
    - redis

  redis:
    image: 'bitnami/redis:latest'
    environment:
      REDIS_PASSWORD: test-pass
    ports:
      - "6379:6379"