version: "3"
services:
  kntrl:
    image: kntrl/self-hosted:0.10.0
    volumes:
    - "./kntrl.json5:/kntrl/kntrl.json5"
    ports:
    - "9876:9876"

  maildev:
    image: maildev/maildev
    ports:
    - "1080:1080"
    - "1025:1025"